// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqfsohxbafdcjwbheuwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxZnNvaHhiYWZkY2p3YmhldXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzODYyOTAsImV4cCI6MjA1Njk2MjI5MH0.XURQOl1PB0DFjgD6ZPBx-wEIysxaoqYg6M6BoGFlEmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);